### ISSUE TITLE
Cabal configure problem (Haskell 8.4.2 and striot-0.1.0.4)

### ISSUE THREAD

**Issue by PaulWatson9994** [striot/striot#19]
I've just upgraded to haskell 8.4.2 on Windows 10. When I try to run  `cabal configure`  I hit the problem:
-----
```
$ cabal configure
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
[__0] trying: striot-0.1.0.4 (user goal)
[__1] next goal: base (dependency of striot)
[__1] rejecting: base-4.11.1.0/installed-4.1... (conflict: striot => base>=4.9
&& <4.10)
[__1] fail (backjumping, conflict set: base, striot)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: striot, base
Trying configure anyway.
Configuring striot-0.1.0.4...
cabal.exe: Encountered missing dependencies:
HTF -any, base ==4.9.*, time ==1.6.*
```
Anyone any ideas how to fix this?

**Comment by adam-cattermole** [comment]
I believe the issue is caused by the base package for Haskell 8.4.2 being `base-4.11.1.0`, which we have restricted in our build file as `<4.10`. Changing the dependency in the `striot.cabal` file [L22](https://github.com/striot/striot/blob/master/striot.cabal#L22) and [L29](https://github.com/striot/striot/blob/master/striot.cabal#L29) would potentially fix this error, but could introduce others. I do not know which versions of the packages we use are compatible with one another, and whether they are all supported in Haskell 8.4.2, but I'll have a look tomorrow and get back to you.

**Comment by PaulWatson9994** [comment]
Hi Adam

That’s really helpful thanks.. I’ll revert to 8.2.1

Regards
Paul
