### ISSUE TITLE
Re-design of the Event type

### ISSUE THREAD

**Issue by PaulWatson9994** [striot/striot#22]
Georgy suggested that we change the definition of the event type using Maybe to avoid partial functions. I've had a try at this, but would value feedback before going further as making the change will have implications for FunctionalIoTtypes and any examples that generate test data.

```
module FunctionalIoTtypes where
import Data.Time (UTCTime) -- http://two-wrongs.com/haskell-time-library-tutorial

data Event alpha     =  Event {eventId :: Int, time :: Maybe Timestamp, value :: Maybe alpha}
     deriving (Eq, Ord, Show, Read)

type Timestamp       = UTCTime
type Stream alpha    = [Event alpha]

dataEvent :: Event alpha -> Bool
dataEvent (Event eid t (Just v)) = True
dataEvent (Event eid t Nothing)  = False

getData :: Event alpha -> alpha
getData   (Event eid t (Just v)) = v

timedEvent :: Event alpha -> Bool
timedEvent (Event eid (Just t) v) = True
timedEvent (Event eid Nothing  v) = False

getTime :: Event alpha -> Timestamp
getTime (Event eid (Just t) v) = t
```

**Comment by PaulWatson9994** [comment]
I've also taken the opportunity to rename the id so as to avoid the clash with the prelude raised in issue 3.

**Comment by geo2a** [comment]
Hello Paul,

I think that the new definition of the event type is idiomatic Haskell and is much less confusing and dangerous than the old one.

My only concern here is that the `getData` and `getTime` functions are still partial: they can still be applied to a non-data/time event:

```haskell
foo :: Event Char
foo = Event 42 Nothing (Just 'a')

-- This function compiles but will cause a run time error
-- since `getTime (Event eid Nothing v)` is undefined. 
runTimeError = getTime foo 
```
The `getTime` and `getData` functions behave like that because they are in fact analogous to the `fromJust` function from the standard `Data.Maybe` module:

```
fromJust :: Maybe a -> a
fromJust Nothing  = errorWithoutStackTrace "Maybe.fromJust: Nothing"
fromJust (Just x) = x
```  

I think it is better, and more consistent, to just use the record fields `time` and `value` (or pattern matching) directly in the code. This will be typesafe.
